platform: x64
environment:
 matrix:
  - DC: dmd
    arch: x86

skip_tags: false

install:
  - ps: |
      #$latest = (Invoke-WebRequest "http://downloads.dlang.org/releases/LATEST").toString();
      #$url = "http://downloads.dlang.org/releases/2.x/$($latest)/dmd.$($latest).windows.7z";
      $url = "http://downloads.dlang.org/releases/2.x/2.088.1/dmd.2.088.1.windows.7z"
      (New-Object System.Net.WebClient).DownloadFile($url, "C:\dmd.7z");
      7z x C:\dmd.7z -oC:\ > $null;
      $env:DC="dmd"
      $env:DMD="dmd"
      $env:PATH="$($env:PATH);C:\dmd2\windows\bin;";

build: off

test_script:
 - dub test -b unittest-cov --compiler=%DC%
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
branches:
  only:
    - master
