platform: x64
environment:
 matrix:
  - DC: dmd
    arch: x86

skip_tags: false

install:
  - ps: |
      $latest = (Invoke-WebRequest "http://downloads.dlang.org/releases/LATEST").toString();
      $url = "http://downloads.dlang.org/releases/2.x/$($latest)/dmd.$($latest).windows.7z";
      (New-Object System.Net.WebClient).DownloadFile($url, "C:\dmd.7z");
      $url = "http://downloads.dlang.org/other/omflibs-winsdk-10.0.16299.15.zip";
      (New-Object System.Net.WebClient).DownloadFile($url, "C:\omflibs.zip");
      7z x C:\dmd.7z -oC:\ > $null;
      7z -y x C:\omflibs.zip -oC:\dmd2\windows\lib\ > $null;
      $env:DC="dmd"
      $env:DMD="dmd"
      $env:PATH="$($env:PATH);C:\dmd2\windows\bin;";

build: off

test_script:
 - dub test --compiler=%DC%
